[profile.default]
solc = "0.8.26"
src = "src"
out = "out"
libs = ["lib", "delegate-market"]
via-ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "params_first"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
